import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

const expectedAssets = [
  "caprover-architecture.png",
  "caprover-dashboard.png",
  "caprover-logo.png",
  "caprover-tutorial.gif",
  "caprover-workflow.png",
  "slack-icon.png",
];
const routeManifest = JSON.parse(await readFile("routes.json", "utf8"));
const routeTitleKeys = {
  home: "homepage.hero.titleLine1",
  comparisonHub: "comparisonPages.hub.hero.title",
  coolify: "comparisonPages.coolify.hero.title",
  dokploy: "comparisonPages.dokploy.hero.title",
  dokku: "comparisonPages.dokku.hero.title",
};
const routes = Object.entries(routeManifest).map(([name, route]) => ({
  path: route.path,
  titleKey: routeTitleKeys[name],
}));
const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const assetPath = "homepage-assets";
const locales = JSON.parse(await readFile("../content/locales.json", "utf8"));
const enabledLocales = locales.filter((locale) => locale.enabled);
const defaultLocale = enabledLocales.find((locale) => locale.default);

assert(defaultLocale);

function localizedPath(locale, route) {
  return `${locale.pathPrefix}${route}`;
}

function outputFile(locale, route) {
  return `out${localizedPath(locale, route)}index.html`;
}

async function readCatalog(locale) {
  return JSON.parse(
    await readFile(`../content/${locale.code}/marketing.json`, "utf8"),
  );
}

test("exports complete localized website routes", async () => {
  const defaultHtml = await readFile("out/index.html", "utf8");
  const defaultAlias = await readFile(
    `out/${defaultLocale.code}/index.html`,
    "utf8",
  );

  for (const locale of enabledLocales) {
    const catalog = await readCatalog(locale);
    for (const route of routes) {
      const html = await readFile(outputFile(locale, route.path), "utf8");
      assert(
        html.includes(catalog[route.titleKey]),
        `${locale.code}${route.path} is missing localized content`,
      );
      assert(
        html.includes(
          `https://caprover.com${localizedPath(locale, route.path)}`,
        ),
        `${locale.code}${route.path} is missing its canonical URL`,
      );
    }

    const homepage = await readFile(outputFile(locale, "/"), "utf8");
    assert(
      homepage.includes(
        `https://caprover.com${locale.pathPrefix}/docs/get-started`,
      ),
    );
    for (const targetLocale of enabledLocales) {
      assert(homepage.includes(`hrefLang="${targetLocale.code}"`));
    }
  }

  assert(defaultAlias.includes(defaultLocale.code));
  assert(defaultAlias.includes("noindex, follow"));

  await Promise.all(
    expectedAssets.map((asset) => access(`out/${assetPath}/${asset}`)),
  );

  for (const asset of expectedAssets) {
    assert.match(
      defaultHtml,
      new RegExp(`(?:href|src)=["']${basePath}/${assetPath}/${asset}["']`),
    );
  }

  if (basePath) {
    assert.match(defaultHtml, new RegExp(`href=["']${basePath}/_next/`));
  }
});

test("keeps comparison regressions covered across locales", async () => {
  const homepage = await readFile(
    `out${routeManifest.home.path}index.html`,
    "utf8",
  );
  const hub = await readFile(
    `out${routeManifest.comparisonHub.path}index.html`,
    "utf8",
  );
  const coolify = await readFile(
    `out${routeManifest.coolify.path}index.html`,
    "utf8",
  );
  const dokploy = await readFile(
    `out${routeManifest.dokploy.path}index.html`,
    "utf8",
  );
  const dokku = await readFile(
    `out${routeManifest.dokku.path}index.html`,
    "utf8",
  );
  const sitemap = await readFile("out/sitemap.xml", "utf8");

  assert.doesNotMatch(homepage, /href=["'][^"']*\/compare\/?["']/);
  assert.match(hub, /Start simple\. Never hit a ceiling\./);
  assert.match(hub, /SIMPLE BY DEFAULT/);
  assert.match(hub, /SMALL-SERVER FRIENDLY/);
  assert.match(hub, /status-yes/);
  assert.match(coolify, /CAPROVER VS COOLIFY/);
  assert.match(dokploy, /CAPROVER VS DOKPLOY/);
  assert.match(dokku, /CAPROVER VS DOKKU/);

  for (const matchup of [coolify, dokploy, dokku]) {
    assert.match(matchup, /SIMPLE BY DEFAULT/);
    assert.match(matchup, /POWERFUL WHEN NEEDED/);
    assert.match(matchup, /SMALL-SERVER FRIENDLY/);
    assert.match(matchup, /status-yes/);
    assert.doesNotMatch(matchup, /Raw Docker ServiceUpdate override/);
  }
  for (const comparisonPage of [hub, coolify, dokploy, dokku]) {
    assert.match(
      comparisonPage,
      /This comparison table was generated by an AI agent/,
    );
    assert.match(comparisonPage, /mailto:marketing@caprover\.com/);
  }
  assert.doesNotMatch(coolify, /Moving to Coolify/);
  assert.doesNotMatch(dokploy, /Moving to Dokploy/);
  assert.doesNotMatch(dokku, /Moving to Dokku/);

  for (const locale of enabledLocales) {
    for (const route of routes) {
      assert(
        sitemap.includes(
          `https://caprover.com${localizedPath(locale, route.path)}`,
        ),
      );
    }
  }
});

test("enabled marketing catalogs preserve source keys and structural values", async () => {
  const source = await readCatalog(defaultLocale);

  for (const locale of enabledLocales) {
    const catalog = await readCatalog(locale);
    assert.deepEqual(Object.keys(catalog).sort(), Object.keys(source).sort());
    for (const [key, value] of Object.entries(source)) {
      if (key.endsWith(".key") || key.endsWith(".status")) {
        assert.equal(catalog[key], value, `${locale.code}: ${key}`);
      }
    }
  }
});
