import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

const expectedAssets = [
  "caprover-architecture.png",
  "caprover-dashboard.png",
  "caprover-logo.png",
  "caprover-tutorial.gif",
  "caprover-workflow.png",
  "slack-icon.png",
];
const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const assetPath = "homepage-assets";

test("exports a complete static homepage", async () => {
  const html = await readFile("out/index.html", "utf8");

  assert.match(html, /<title>CapRover · Scalable, Free and Self-hosted PaaS<\/title>/);
  assert.match(html, /Deploy apps\./);
  assert.match(html, /lang="en"/);
  assert.match(html, /<details class="language-switch">/);
  assert.match(html, /href=["']\/zh-CN\/["']/);
  assert.match(html, />English<\/a>/);
  assert.match(html, />中文<\/a>/);

  await Promise.all(
    expectedAssets.map((asset) => access(`out/${assetPath}/${asset}`)),
  );

  for (const asset of expectedAssets) {
    assert.match(
      html,
      new RegExp(`(?:href|src)=["']${basePath}/${assetPath}/${asset}["']`),
    );
  }

  if (basePath) {
    assert.match(html, new RegExp(`href=["']${basePath}/_next/`));
  }
});

test("exports a Simplified Chinese homepage that points at Chinese docs", async () => {
  const html = await readFile("out/zh-CN/index.html", "utf8");

  assert.match(html, /lang="zh-CN"/);
  assert.match(html, /部署应用/);
  assert.match(html, /掌控自己的/);
  assert.match(html, /href=["']\/docs\/zh-CN\/get-started\.html["']/);
  assert.doesNotMatch(html, /href=["'][^"']*\/compare\/?["']/);
});

test("exports the comparison hub and one-on-one pages without changing homepage navigation", async () => {
  const homepage = await readFile("out/index.html", "utf8");
  const hub = await readFile("out/compare/index.html", "utf8");
  const coolify = await readFile("out/compare/coolify/index.html", "utf8");
  const dokploy = await readFile("out/compare/dokploy/index.html", "utf8");
  const dokku = await readFile("out/compare/dokku/index.html", "utf8");
  const sitemap = await readFile("out/sitemap.xml", "utf8");

  assert.doesNotMatch(homepage, /href=["'][^"']*\/compare\/?["']/);
  assert.match(hub, /Start simple\. Never hit a ceiling\./);
  assert.match(hub, /SIMPLE BY DEFAULT/);
  assert.match(hub, /SMALL-SERVER FRIENDLY/);
  assert.match(hub, /status-yes/);
  assert.match(coolify, /CAPROVER VS COOLIFY/);
  assert.match(dokploy, /CAPROVER VS DOKPLOY/);
  assert.match(dokku, /CAPROVER VS DOKKU/);
  for (const matchup of [coolify, dokploy, dokku]) {
    assert.match(matchup, /SIMPLE BY DEFAULT/);
    assert.match(matchup, /POWERFUL WHEN NEEDED/);
    assert.match(matchup, /SMALL-SERVER FRIENDLY/);
    assert.match(matchup, /status-yes/);
    assert.doesNotMatch(matchup, /Raw Docker ServiceUpdate override/);
  }
  for (const comparisonPage of [hub, coolify, dokploy, dokku]) {
    assert.match(comparisonPage, /This comparison table was generated by an AI agent/);
    assert.match(comparisonPage, /mailto:marketing@caprover\.com/);
  }
  assert.doesNotMatch(coolify, /Moving to Coolify/);
  assert.doesNotMatch(dokploy, /Moving to Dokploy/);
  assert.doesNotMatch(dokku, /Moving to Dokku/);
  assert.match(sitemap, /https:\/\/caprover\.com\/compare\/coolify\//);
  assert.match(sitemap, /https:\/\/caprover\.com\/zh-CN\/compare\/coolify\//);
});

test("exports Simplified Chinese comparison pages", async () => {
  const hub = await readFile("out/zh-CN/compare/index.html", "utf8");
  const coolify = await readFile("out/zh-CN/compare/coolify/index.html", "utf8");
  const dokploy = await readFile("out/zh-CN/compare/dokploy/index.html", "utf8");
  const dokku = await readFile("out/zh-CN/compare/dokku/index.html", "utf8");

  assert.match(hub, /lang="zh-CN"/);
  assert.match(hub, /从简单开始，不必碰到天花板。/);
  assert.match(hub, /默认简单/);
  assert.match(hub, /适合小规格服务器/);
  assert.match(coolify, /CAPROVER VS COOLIFY/);
  assert.match(dokploy, /CAPROVER VS DOKPLOY/);
  assert.match(dokku, /CAPROVER VS DOKKU/);
  for (const page of [hub, coolify, dokploy, dokku]) {
    assert.match(page, /此对比表由 AI 代理生成/);
    assert.match(page, /mailto:marketing@caprover\.com/);
    assert.match(page, /href=["']\/docs\/zh-CN\/get-started\.html["']/);
  }
});
